# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 379b040f40a526bb842105fc68265a7c4a4c1532e86822d8f4c645a7ac53a92b7d19644a5bf6ccdca94dabc2110b34f684b71dd3af588791d405d9a9d1470b70

test:
  secret_key_base: 80ab5500b33e53abda127164ad0b51717f265945210170c68d7ab06dd36c099b70ae4e66e31e8bbdc7a2e4cb25054289da0b20bf1d4ce2b7704214b25976d172

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
