# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 942abe434a863adfbd265386caee9bf93464f67cab93fda4852bb4e6f2d8d26161fc8f506e82ab2a28b2b10e39ea3d69bba31c51c32a5affe0d92bd5cdaa2213

test:
  secret_key_base: b3b80f1203b2a98478350a967bc9d0f7b116f47daedd58cf861dc31e6b3273b3e5b30f6b826b86b7066f3fcc0557119426e04c45c58ed5336f815806c57e0086

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
