# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d4fb9a82cbe1e9ab5a4b7243214564527660ca01bacf575ab4daac52af35fe093c26d054fc6c3ed1123d53e3798c003e34b775b5a0c9afaaa7bd2caf624f0972

test:
  secret_key_base: 76aad3e4e465a2f33a3d532f7cd1a501479b85680fe8aef20a15fdc3ac9cca2f287854032048007eb59095d029d6fdd39b0f4cc5aa7325d1992c8a5c1984d045

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
